# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

use_frameworks!

target 'SmartFeed' do
    pod 'Realm', '0.98.5'
    pod 'Alamofire', '3.3.0'
    pod 'AlamofireObjectMapper', '2.1.2'
    pod 'ObjectMapper', '1.1.5'
    pod 'DZReadability', '0.2.3'
end

target 'SmartFeedTests' do

end

target 'SmartFeedUITests' do

end

