# Uncomment this line to define a global platform for your project
# platform :ios, '9.2'

inhibit_all_warnings!
use_frameworks!

target 'SmartFeed' do
    pod 'RealmSwift', '~> 0.98.5'

    pod 'Alamofire', '~> 3.3.0'
#    pod 'ObjectMapper', '1.1.5'
#    pod 'AlamofireObjectMapper', '~> 2.1.2'
#    pod 'AlamofireImage', '~> 2.2.0'

    pod 'AlamofireXmlToObjects', '1.0.1'
#    pod 'AlamofireNetworkActivityIndicator', '~> 1.0' #XCode 7.3

#pod 'Feeder', '~> 0.1'

#obj-c libs https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html
#    pod 'HTMLReader', '0.9.5'
#    pod 'DZReadability', '0.2.3'
end

target 'SmartFeedTests' do

end

target 'SmartFeedUITests' do

end

